# Site settings
title: melgineer's Blog

author:
  name: Evan Will
  email: your-email@domain.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
theme: minima
#remote_theme: jekyll/minima
