# Site settings
title: melgineer's Blog

author:
  name: Michelle Lynch
  email: your-email@domain.com
description: "A website."

# Build settings
remote_theme: jekyll/minima

plugins:
- jekyll-remote-theme
