# theme: jekyll-theme-minimal
# Site settings
title: melgineer's Blog
description: A webpage

author:
  name: Michelle Lynch
  email: your-email@domain.com

# Build settings
theme: jekyll-theme-minima
#remote_theme: jekyll/minima
