# Site settings
title: melgineer's Blog

author:
  name: Michelle Lynch
  email: your-email@domain.com
description: "A website."

# Build settings
theme: jekyll-theme-modernist
#remote_theme: jekyll/minima

base_url: /melgineer.github.io
repository: melgineer/melgineer.github.io
