# theme: jekyll-theme-minimal
# Site settings
title: melgineer's Blog... xxx
description: A webpage

author:
  name: Michelle Lynch
  email: your-email@domain.com

# Build settings
remote_theme: jekyll/minima
